export { default as Specification } from './Specification/Specification';
export { default as Banner } from './Banner/Banner';
export { default as Contact } from './Contact/Contact';
export { default as SidebarHome } from './SidebarHome/SidebarHome';
export { default as Services } from './Services/Services';
export { default as Staff } from './Staff/Staff';
export { default as FeedBack } from './FeedBack/FeedBack';
export { default as Intro } from './Intro/Intro';
export { default as ScrollTop } from './ScrollTop/ScrollTop';
